### PR TITLE
promise support

### LINKED ISSUE #3: Return promise if no callback is given
Promises are now native on Node.js and `async`/`await` is enabled by default in babel. How about making this library compatible?

It could work like this; when no callback is given a promise is returned instead. This could then be used, e.g. as this:

```javascript
async function myCoolTests () {
  // ...

  const a = fs.createReadStream('a.bmp')
  const b = fs.createReadStream('b.bmp')

  const equal = await streamEqual(a, b)

  // ...
}
```

I could write a pull request if you want to :+1:

### PR DESCRIPTION
**Pull request by LinusU**
Fixes #3 :100: :tada: 

I think I managed to follow your styling. I can personally recommend adding [feross/standard](https://github.com/feross/standard) or similar to the project to help with this in the future.

### CODE REVIEW

**Comment by fent** [comment]
I'm hesitant on this since it would mean I have to consider making all of my other modules thenables as well. And even though promises are now in node core, from a quick look at the docs, it doesn't seem like their async functions return promises. Do they?

Are promises really used that much more now by the node community? I haven't worked on node specific projects, other than my own modules, for a while now so I may be out of the loop.

As for standard, I've seen it before. I'm hesitant to switch to that from jshint since it would mean rewriting all of my files since they contain semicolons, and that's a lot of commit blame history that'll get overwritten.

Other than that, looks like a pretty good PR.

**Comment by LinusU** [comment]
I understand exactly where you are coming from, and I feel the same. The Node.js core api doesn't return promises, but this is a bit of chicken and egg problem. Node core will be one of the last to implement it since it must follow what the community. There is a lot of talk about it thought.

I've seen a very large increase in promise usage lately and it feels like this is where the community is heading. For good or bad.

When `async`/`await` becomes supported by node I really think that we will hit a break point where even more people will want to switch. The more module which already has support the better.

The thing that has put me over the edge to start supporting promises in my libraries is that it doesn't require any extra dependencies, and often is just a few lines of code.

Of course the decision is entirely up to you.

**Comment by fent** [comment]
Thanks for the PR!

**Comment by LinusU** [comment]
Thank you!

**Pull request merged**
