### PR TITLE
Add typescript typings

### PR DESCRIPTION
**Pull request by ethanresnick**
This PR would add type declarations so that typescript users are given type checking and smarter autocomplete when using the library.

The format for the typings follows the standard typescript [template](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html) for modules whose export is a function.

### CODE REVIEW

**Comment by fent** [comment]
Thanks for the PR!

But I'm not too familiar with typings since I haven't use Typescript in a while. How can I test that this is working properly?

**Comment by ethanresnick** [comment]
Sure thing. I really appreciate the library!

I created [a gist](https://gist.github.com/ethanresnick/9cc90bb2feffb30d1ed435a878e1c3be) with the minimal files needed to test this. If you put all those files in a folder and run `npm install`, you'll have a typescript project where you can play with the code in `test.ts` and make sure that it compiles when the types are right but fails when they aren't. (To compile the project, just run `node_modules/.bin/tsc -p .` from the project directory.)

Basically, the tsconfig.json just configures the typescript compiler so that it knows, e.g., to look for the typings in `node_modules` (that's the `moduleResolution` setting) and to load typings for ES6 (so `Promise` is defined). 

The package.json points to my fork of the module so that you'll get the typings on install, and uses Typescript 2, since older versions of typescript don't support various things we want here (e.g., referring to the `null` type directly, using the "lib" compiler setting, using the `<reference types` directive, etc).

**Comment by fent** [comment]
I'm getting the following when the run the `node_modules/.bin/tsc -p .` command

```
node_modules/stream-equal/lib/index.d.ts(1,1): error TS2688: Cannot find type definition file for 'node'.
node_modules/stream-equal/lib/index.d.ts(3,39): error TS2503: Cannot find namespace 'NodeJS'.
node_modules/stream-equal/lib/index.d.ts(3,71): error TS2503: Cannot find namespace 'NodeJS'.
node_modules/stream-equal/lib/index.d.ts(4,39): error TS2503: Cannot find namespace 'NodeJS'.
node_modules/stream-equal/lib/index.d.ts(4,71): error TS2503: Cannot find namespace 'NodeJS'.
test.ts(1,21): error TS2307: Cannot find module 'fs'.
test.ts(12,3): error TS2304: Cannot find name 'console'.
```

**Comment by ethanresnick** [comment]
Looks like all those errors are because the typings for node (which has fs, console, etc.) couldn't be found. I've updated my PR to make stream-equal depend on the node typings, so things should work now if you `npm install` again. It's weird this wasn't happening on my computer though...maybe I'm somehow getting the node typings from a global source.

**Comment by fent** [comment]
Now it's working. :)

But I'm not sure of including an extra package as part of the dependencies, for those that don't use TypeScript. Can we figure out the way you are getting the typings from a global source? Maybe other TypeScript users are getting them the same way, in which case we won't need to add the dependency.

**Comment by ethanresnick** [comment]
Ok, I figured out how I was getting the typings before: I accidentally had a `node_modules` folder in a directory above the project directory, and that folder had the node typings in it, so typescript was picking them up. That's probably not generalizable for others, though. 

We could require users do `npm install @types/node` manually, but I don't think that's best practice; including the types as a package.json dependency comes straight from an [instruction/example](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies) on the typescript website. Also, if a user depends on a package that in turn depends on your package, they might not even see your docs, so it could be confusing for them to figure out what to do.

I'm generally not a fan of extra dependencies either, but I think there are some mitigating factors here, namely: 1) the `@types/node` dependency is only [one file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/types-2.0/node/index.d.ts), so it's not using much disk space; 2) it doesn't install any javascript code, just the inert type definitions, so there's no risk of it messing up something at runtime; and 3) the contents are managed by Microsoft through DefinitelyTyped, so there's little security risk.

**Comment by fent** [comment]
That's a good justification for it. I'm a bit surprised the `@types/node` as well as types for other environments isn't included in the compiler by default.

Thank you again for the PR! Merged and published.

**Pull request merged**
